<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="2" total="9" passed="5">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="22282" started-at="2018-08-29T17:04:14Z" finished-at="2018-08-29T17:04:37Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="22282" started-at="2018-08-29T17:04:14Z" finished-at="2018-08-29T17:04:37Z">
      <class name="com.facebook.TestCases.LoginUI_Test">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.facebook.TestCases.LoginUI_Test@7d9d1a19]" name="setUp" is-config="true" duration-ms="406" started-at="2018-08-29T22:34:14Z" finished-at="2018-08-29T22:34:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="BeforeTest()[pri:0, instance:com.facebook.TestCases.LoginUI_Test@7d9d1a19]" name="BeforeTest" is-config="true" duration-ms="7731" started-at="2018-08-29T22:34:14Z" finished-at="2018-08-29T22:34:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeTest -->
        <test-method status="PASS" signature="register(java.lang.reflect.Method)[pri:0, instance:com.facebook.TestCases.LoginUI_Test@7d9d1a19]" name="register" is-config="true" duration-ms="452" started-at="2018-08-29T22:34:22Z" finished-at="2018-08-29T22:34:22Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.facebook.TestCases.LoginUI_Test.testOne() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- register -->
        <test-method status="PASS" signature="testOne()[pri:1, instance:com.facebook.TestCases.LoginUI_Test@7d9d1a19]" name="testOne" duration-ms="3566" started-at="2018-08-29T22:34:22Z" finished-at="2018-08-29T22:34:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testOne -->
        <test-method status="PASS" signature="captureStatus(org.testng.ITestResult)[pri:0, instance:com.facebook.TestCases.LoginUI_Test@7d9d1a19]" name="captureStatus" is-config="true" duration-ms="17" started-at="2018-08-29T22:34:26Z" finished-at="2018-08-29T22:34:26Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testOne status=SUCCESS method=LoginUI_Test.testOne()[pri:1, instance:com.facebook.TestCases.LoginUI_Test@7d9d1a19] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureStatus -->
        <test-method status="PASS" signature="register(java.lang.reflect.Method)[pri:0, instance:com.facebook.TestCases.LoginUI_Test@7d9d1a19]" name="register" is-config="true" duration-ms="308" started-at="2018-08-29T22:34:26Z" finished-at="2018-08-29T22:34:26Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.facebook.TestCases.LoginUI_Test.testOneTwo() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- register -->
        <test-method status="SKIP" signature="testOneTwo()[pri:2, instance:com.facebook.TestCases.LoginUI_Test@7d9d1a19]" name="testOneTwo" duration-ms="463" started-at="2018-08-29T22:34:26Z" finished-at="2018-08-29T22:34:27Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.facebook.TestCases.LoginUI_Test.testOneTwo(LoginUI_Test.java:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testOneTwo -->
        <test-method status="PASS" signature="captureStatus(org.testng.ITestResult)[pri:0, instance:com.facebook.TestCases.LoginUI_Test@7d9d1a19]" name="captureStatus" is-config="true" duration-ms="160" started-at="2018-08-29T22:34:27Z" finished-at="2018-08-29T22:34:27Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testOneTwo status=SKIP method=LoginUI_Test.testOneTwo()[pri:2, instance:com.facebook.TestCases.LoginUI_Test@7d9d1a19] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureStatus -->
        <test-method status="PASS" signature="register(java.lang.reflect.Method)[pri:0, instance:com.facebook.TestCases.LoginUI_Test@7d9d1a19]" name="register" is-config="true" duration-ms="324" started-at="2018-08-29T22:34:27Z" finished-at="2018-08-29T22:34:28Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.facebook.TestCases.LoginUI_Test.testOneTwo() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- register -->
        <test-method status="FAIL" signature="testOneTwo()[pri:2, instance:com.facebook.TestCases.LoginUI_Test@7d9d1a19]" name="testOneTwo" duration-ms="490" started-at="2018-08-29T22:34:28Z" finished-at="2018-08-29T22:34:28Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.facebook.TestCases.LoginUI_Test.testOneTwo(LoginUI_Test.java:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:967)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testOneTwo -->
        <test-method status="PASS" signature="captureStatus(org.testng.ITestResult)[pri:0, instance:com.facebook.TestCases.LoginUI_Test@7d9d1a19]" name="captureStatus" is-config="true" duration-ms="122" started-at="2018-08-29T22:34:28Z" finished-at="2018-08-29T22:34:28Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testOneTwo status=FAILURE method=LoginUI_Test.testOneTwo()[pri:2, instance:com.facebook.TestCases.LoginUI_Test@7d9d1a19] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureStatus -->
        <test-method status="PASS" signature="register(java.lang.reflect.Method)[pri:0, instance:com.facebook.TestCases.LoginUI_Test@7d9d1a19]" name="register" is-config="true" duration-ms="312" started-at="2018-08-29T22:34:28Z" finished-at="2018-08-29T22:34:29Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.facebook.TestCases.LoginUI_Test.testTwo() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- register -->
        <test-method status="PASS" signature="testTwo()[pri:5, instance:com.facebook.TestCases.LoginUI_Test@7d9d1a19]" name="testTwo" duration-ms="628" started-at="2018-08-29T22:34:29Z" finished-at="2018-08-29T22:34:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTwo -->
        <test-method status="PASS" signature="captureStatus(org.testng.ITestResult)[pri:0, instance:com.facebook.TestCases.LoginUI_Test@7d9d1a19]" name="captureStatus" is-config="true" duration-ms="1" started-at="2018-08-29T22:34:29Z" finished-at="2018-08-29T22:34:29Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testTwo status=SUCCESS method=LoginUI_Test.testTwo()[pri:5, instance:com.facebook.TestCases.LoginUI_Test@7d9d1a19] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureStatus -->
        <test-method status="PASS" signature="register(java.lang.reflect.Method)[pri:0, instance:com.facebook.TestCases.LoginUI_Test@7d9d1a19]" name="register" is-config="true" duration-ms="495" started-at="2018-08-29T22:34:29Z" finished-at="2018-08-29T22:34:30Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.facebook.TestCases.LoginUI_Test.testThree()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- register -->
        <test-method status="PASS" signature="testThree()[pri:10, instance:com.facebook.TestCases.LoginUI_Test@7d9d1a19]" name="testThree" duration-ms="495" started-at="2018-08-29T22:34:30Z" finished-at="2018-08-29T22:34:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testThree -->
        <test-method status="PASS" signature="captureStatus(org.testng.ITestResult)[pri:0, instance:com.facebook.TestCases.LoginUI_Test@7d9d1a19]" name="captureStatus" is-config="true" duration-ms="3" started-at="2018-08-29T22:34:30Z" finished-at="2018-08-29T22:34:30Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testThree status=SUCCESS method=LoginUI_Test.testThree()[pri:10, instance:com.facebook.TestCases.LoginUI_Test@7d9d1a19] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureStatus -->
        <test-method status="PASS" signature="register(java.lang.reflect.Method)[pri:0, instance:com.facebook.TestCases.LoginUI_Test@7d9d1a19]" name="register" is-config="true" duration-ms="320" started-at="2018-08-29T22:34:30Z" finished-at="2018-08-29T22:34:30Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.facebook.TestCases.LoginUI_Test.testFour()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- register -->
        <test-method status="PASS" signature="testFour()[pri:15, instance:com.facebook.TestCases.LoginUI_Test@7d9d1a19]" name="testFour" duration-ms="718" started-at="2018-08-29T22:34:30Z" finished-at="2018-08-29T22:34:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFour -->
        <test-method status="PASS" signature="captureStatus(org.testng.ITestResult)[pri:0, instance:com.facebook.TestCases.LoginUI_Test@7d9d1a19]" name="captureStatus" is-config="true" duration-ms="2" started-at="2018-08-29T22:34:31Z" finished-at="2018-08-29T22:34:31Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testFour status=SUCCESS method=LoginUI_Test.testFour()[pri:15, instance:com.facebook.TestCases.LoginUI_Test@7d9d1a19] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureStatus -->
        <test-method status="PASS" signature="register(java.lang.reflect.Method)[pri:0, instance:com.facebook.TestCases.LoginUI_Test@7d9d1a19]" name="register" is-config="true" duration-ms="417" started-at="2018-08-29T22:34:31Z" finished-at="2018-08-29T22:34:32Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.facebook.TestCases.LoginUI_Test.testFive()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- register -->
        <test-method status="SKIP" signature="testFive()[pri:16, instance:com.facebook.TestCases.LoginUI_Test@7d9d1a19]" name="testFive" duration-ms="426" started-at="2018-08-29T22:34:32Z" finished-at="2018-08-29T22:34:32Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.facebook.TestCases.LoginUI_Test.testFive(LoginUI_Test.java:238)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFive -->
        <test-method status="PASS" signature="captureStatus(org.testng.ITestResult)[pri:0, instance:com.facebook.TestCases.LoginUI_Test@7d9d1a19]" name="captureStatus" is-config="true" duration-ms="448" started-at="2018-08-29T22:34:32Z" finished-at="2018-08-29T22:34:33Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testFive status=SKIP method=LoginUI_Test.testFive()[pri:16, instance:com.facebook.TestCases.LoginUI_Test@7d9d1a19] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureStatus -->
        <test-method status="PASS" signature="register(java.lang.reflect.Method)[pri:0, instance:com.facebook.TestCases.LoginUI_Test@7d9d1a19]" name="register" is-config="true" duration-ms="299" started-at="2018-08-29T22:34:33Z" finished-at="2018-08-29T22:34:33Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.facebook.TestCases.LoginUI_Test.testFive()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- register -->
        <test-method status="FAIL" signature="testFive()[pri:16, instance:com.facebook.TestCases.LoginUI_Test@7d9d1a19]" name="testFive" duration-ms="543" started-at="2018-08-29T22:34:33Z" finished-at="2018-08-29T22:34:34Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.facebook.TestCases.LoginUI_Test.testFive(LoginUI_Test.java:238)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:967)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFive -->
        <test-method status="PASS" signature="captureStatus(org.testng.ITestResult)[pri:0, instance:com.facebook.TestCases.LoginUI_Test@7d9d1a19]" name="captureStatus" is-config="true" duration-ms="1470" started-at="2018-08-29T22:34:34Z" finished-at="2018-08-29T22:34:35Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testFive status=FAILURE method=LoginUI_Test.testFive()[pri:16, instance:com.facebook.TestCases.LoginUI_Test@7d9d1a19] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureStatus -->
        <test-method status="PASS" signature="register(java.lang.reflect.Method)[pri:0, instance:com.facebook.TestCases.LoginUI_Test@7d9d1a19]" name="register" is-config="true" duration-ms="284" started-at="2018-08-29T22:34:35Z" finished-at="2018-08-29T22:34:35Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.facebook.TestCases.LoginUI_Test.testSix()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- register -->
        <test-method status="PASS" signature="testSix()[pri:20, instance:com.facebook.TestCases.LoginUI_Test@7d9d1a19]" name="testSix" duration-ms="466" started-at="2018-08-29T22:34:35Z" finished-at="2018-08-29T22:34:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSix -->
        <test-method status="PASS" signature="captureStatus(org.testng.ITestResult)[pri:0, instance:com.facebook.TestCases.LoginUI_Test@7d9d1a19]" name="captureStatus" is-config="true" duration-ms="1" started-at="2018-08-29T22:34:36Z" finished-at="2018-08-29T22:34:36Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testSix status=SUCCESS method=LoginUI_Test.testSix()[pri:20, instance:com.facebook.TestCases.LoginUI_Test@7d9d1a19] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureStatus -->
        <test-method status="PASS" signature="cleanUp()[pri:0, instance:com.facebook.TestCases.LoginUI_Test@7d9d1a19]" name="cleanUp" is-config="true" duration-ms="685" started-at="2018-08-29T22:34:36Z" finished-at="2018-08-29T22:34:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanUp -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:com.facebook.TestCases.LoginUI_Test@7d9d1a19]" name="afterSuite" is-config="true" duration-ms="1" started-at="2018-08-29T22:34:37Z" finished-at="2018-08-29T22:34:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.facebook.TestCases.LoginUI_Test@7d9d1a19]" name="tearDown" is-config="true" duration-ms="6897" started-at="2018-08-29T22:34:37Z" depends-on-methods="com.facebook.TestCases.LoginUI_Test.afterSuite" finished-at="2018-08-29T22:34:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.facebook.TestCases.LoginUI_Test -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
